package com.example.material.entity;

/**
 * Twiduserm generated by MyEclipse Persistence Tools
 */
@SuppressWarnings("serial")
public class User implements java.io.Serializable {

	// Fields

	private String userId;
	private String userName;
	private String password;
	private String authorityType;
	private String authAdminValid;
	private String requestValid;
	private String recieveValid;
	private String responseValid;
	
	public String getUserId() {
		return userId;
	}
	public void setUserId(String userId) {
		this.userId = userId;
	}
	public String getUserName() {
		return userName;
	}
	public void setUserName(String userName) {
		this.userName = userName;
	}
	public String getPassword() {
		return password;
	}
	public void setPassword(String password) {
		this.password = password;
	}
	public String getAuthorityType() {
		return authorityType;
	}
	public void setAuthorityType(String authorityType) {
		this.authorityType = authorityType;
	}
	public String getAuthAdminValid() {
		return authAdminValid;
	}
	public void setAuthAdminValid(String authAdminValid) {
		this.authAdminValid = authAdminValid;
	}
	public String getRequestValid() {
		return requestValid;
	}
	public void setRequestValid(String requestValid) {
		this.requestValid = requestValid;
	}
	public String getRecieveValid() {
		return recieveValid;
	}
	public void setRecieveValid(String recieveValid) {
		this.recieveValid = recieveValid;
	}
	public String getResponseValid() {
		return responseValid;
	}
	public void setResponseValid(String responseValid) {
		this.responseValid = responseValid;
	}





}